import type { User, Workspace, Category, Todo, Label, Comment, ChecklistItem, Notification, ActivityLog } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'ahmet',
    display_name: 'Ahmet Yilmaz',
    avatar_color: '#3b82f6',
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    username: 'elif',
    display_name: 'Elif Demir',
    avatar_color: '#10b981',
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'user-3',
    username: 'mehmet',
    display_name: 'Mehmet Kaya',
    avatar_color: '#f59e0b',
    status: 'away',
    last_seen: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'user-4',
    username: 'zeynep',
    display_name: 'Zeynep Arslan',
    avatar_color: '#ef4444',
    status: 'busy',
    last_seen: new Date().toISOString(),
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'user-5',
    username: 'can',
    display_name: 'Can Ozturk',
    avatar_color: '#8b5cf6',
    status: 'offline',
    last_seen: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    created_at: '2024-01-05T00:00:00Z',
  },
];

// Mock Labels
export const mockLabels: Label[] = [
  { id: 'label-1', workspace_id: 'ws-1', name: 'Bug', color: '#ef4444' },
  { id: 'label-2', workspace_id: 'ws-1', name: 'Feature', color: '#3b82f6' },
  { id: 'label-3', workspace_id: 'ws-1', name: 'Enhancement', color: '#10b981' },
  { id: 'label-4', workspace_id: 'ws-1', name: 'Documentation', color: '#8b5cf6' },
  { id: 'label-5', workspace_id: 'ws-1', name: 'Urgent', color: '#f59e0b' },
  { id: 'label-6', workspace_id: 'ws-1', name: 'Backend', color: '#06b6d4' },
  { id: 'label-7', workspace_id: 'ws-1', name: 'Frontend', color: '#ec4899' },
  { id: 'label-8', workspace_id: 'ws-1', name: 'Design', color: '#f97316' },
];

// Mock Workspace
export const mockWorkspace: Workspace = {
  id: 'ws-1',
  name: 'Proje Yonetimi',
  description: 'Ana calisma alani',
  icon: 'folder',
  created_at: '2024-01-01T00:00:00Z',
  settings: {
    default_view: 'kanban',
    allow_subtasks: true,
    allow_time_tracking: true,
    allow_dependencies: true,
  },
};

// Mock Checklist Items
const mockChecklistItems: Record<string, ChecklistItem[]> = {
  'todo-1': [
    { id: 'check-1', todo_id: 'todo-1', content: 'Gereksinim analizi', is_completed: true, position: 0, completed_at: '2024-01-10T10:00:00Z', completed_by: 'user-1' },
    { id: 'check-2', todo_id: 'todo-1', content: 'Teknik dokuman', is_completed: true, position: 1, completed_at: '2024-01-11T10:00:00Z', completed_by: 'user-1' },
    { id: 'check-3', todo_id: 'todo-1', content: 'UI tasarimi', is_completed: false, position: 2, completed_at: null, completed_by: null },
    { id: 'check-4', todo_id: 'todo-1', content: 'API entegrasyonu', is_completed: false, position: 3, completed_at: null, completed_by: null },
  ],
  'todo-3': [
    { id: 'check-5', todo_id: 'todo-3', content: 'Login sayfasi', is_completed: true, position: 0, completed_at: '2024-01-12T10:00:00Z', completed_by: 'user-2' },
    { id: 'check-6', todo_id: 'todo-3', content: 'Register sayfasi', is_completed: true, position: 1, completed_at: '2024-01-13T10:00:00Z', completed_by: 'user-2' },
    { id: 'check-7', todo_id: 'todo-3', content: 'Sifre sifirlama', is_completed: false, position: 2, completed_at: null, completed_by: null },
  ],
};

// Mock Todos
export const mockTodos: Todo[] = [
  // Backlog
  {
    id: 'todo-1',
    workspace_id: 'ws-1',
    category_id: 'cat-1',
    parent_id: null,
    title: 'Kullanici dashboard tasarimi',
    description: 'Ana kullanici paneli icin modern ve kullanici dostu bir arayuz tasarimi yapilacak. Responsive olmali ve dark mode destegi olmali.',
    status: 'todo',
    priority: 'high',
    position: 0,
    due_date: '2024-02-15T00:00:00Z',
    start_date: '2024-02-01T00:00:00Z',
    completed_at: null,
    estimated_hours: 24,
    actual_hours: null,
    progress: 50,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-1',
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    assignees: [
      { id: 'assign-1', todo_id: 'todo-1', user_id: 'user-1', assigned_at: '2024-01-10T00:00:00Z', user: mockUsers[0] },
      { id: 'assign-2', todo_id: 'todo-1', user_id: 'user-4', assigned_at: '2024-01-10T00:00:00Z', user: mockUsers[3] },
    ],
    labels: [
      { id: 'tl-1', todo_id: 'todo-1', label_id: 'label-2', label: mockLabels[1] },
      { id: 'tl-2', todo_id: 'todo-1', label_id: 'label-8', label: mockLabels[7] },
    ],
    checklist_items: mockChecklistItems['todo-1'],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  {
    id: 'todo-2',
    workspace_id: 'ws-1',
    category_id: 'cat-1',
    parent_id: null,
    title: 'API dokumantasyonu',
    description: 'Tum API endpointleri icin Swagger/OpenAPI dokumantasyonu hazirlanacak.',
    status: 'todo',
    priority: 'medium',
    position: 1,
    due_date: '2024-02-20T00:00:00Z',
    start_date: null,
    completed_at: null,
    estimated_hours: 16,
    actual_hours: null,
    progress: 0,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-2',
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
    assignees: [
      { id: 'assign-3', todo_id: 'todo-2', user_id: 'user-3', assigned_at: '2024-01-12T00:00:00Z', user: mockUsers[2] },
    ],
    labels: [
      { id: 'tl-3', todo_id: 'todo-2', label_id: 'label-4', label: mockLabels[3] },
      { id: 'tl-4', todo_id: 'todo-2', label_id: 'label-6', label: mockLabels[5] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  // In Progress
  {
    id: 'todo-3',
    workspace_id: 'ws-1',
    category_id: 'cat-2',
    parent_id: null,
    title: 'Kullanici kimlik dogrulama sistemi',
    description: 'JWT tabanli kimlik dogrulama sistemi. Social login destegi eklenecek (Google, GitHub).',
    status: 'in_progress',
    priority: 'urgent',
    position: 0,
    due_date: '2024-02-10T00:00:00Z',
    start_date: '2024-01-15T00:00:00Z',
    completed_at: null,
    estimated_hours: 40,
    actual_hours: 28,
    progress: 66,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-1',
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
    assignees: [
      { id: 'assign-4', todo_id: 'todo-3', user_id: 'user-2', assigned_at: '2024-01-08T00:00:00Z', user: mockUsers[1] },
      { id: 'assign-5', todo_id: 'todo-3', user_id: 'user-5', assigned_at: '2024-01-10T00:00:00Z', user: mockUsers[4] },
    ],
    labels: [
      { id: 'tl-5', todo_id: 'todo-3', label_id: 'label-2', label: mockLabels[1] },
      { id: 'tl-6', todo_id: 'todo-3', label_id: 'label-5', label: mockLabels[4] },
      { id: 'tl-7', todo_id: 'todo-3', label_id: 'label-6', label: mockLabels[5] },
    ],
    checklist_items: mockChecklistItems['todo-3'],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [
      { id: 'time-1', todo_id: 'todo-3', user_id: 'user-2', started_at: '2024-01-15T09:00:00Z', ended_at: '2024-01-15T17:00:00Z', duration_minutes: 480, description: 'JWT implementation', user: mockUsers[1] },
      { id: 'time-2', todo_id: 'todo-3', user_id: 'user-2', started_at: '2024-01-16T09:00:00Z', ended_at: '2024-01-16T15:00:00Z', duration_minutes: 360, description: 'OAuth integration', user: mockUsers[1] },
    ],
  },
  {
    id: 'todo-4',
    workspace_id: 'ws-1',
    category_id: 'cat-2',
    parent_id: null,
    title: 'Veritabani optimizasyonu',
    description: 'Yavas sorgularin optimize edilmesi ve index eklenmesi.',
    status: 'in_progress',
    priority: 'high',
    position: 1,
    due_date: '2024-02-12T00:00:00Z',
    start_date: '2024-01-18T00:00:00Z',
    completed_at: null,
    estimated_hours: 20,
    actual_hours: 8,
    progress: 40,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-3',
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-18T00:00:00Z',
    assignees: [
      { id: 'assign-6', todo_id: 'todo-4', user_id: 'user-3', assigned_at: '2024-01-14T00:00:00Z', user: mockUsers[2] },
    ],
    labels: [
      { id: 'tl-8', todo_id: 'todo-4', label_id: 'label-3', label: mockLabels[2] },
      { id: 'tl-9', todo_id: 'todo-4', label_id: 'label-6', label: mockLabels[5] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  // In Review
  {
    id: 'todo-5',
    workspace_id: 'ws-1',
    category_id: 'cat-3',
    parent_id: null,
    title: 'Responsive tasarim duzeltmeleri',
    description: 'Mobil ve tablet gorunumleri icin CSS duzeltmeleri.',
    status: 'in_review',
    priority: 'medium',
    position: 0,
    due_date: '2024-02-08T00:00:00Z',
    start_date: '2024-01-10T00:00:00Z',
    completed_at: null,
    estimated_hours: 12,
    actual_hours: 10,
    progress: 90,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-4',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-22T00:00:00Z',
    assignees: [
      { id: 'assign-7', todo_id: 'todo-5', user_id: 'user-4', assigned_at: '2024-01-05T00:00:00Z', user: mockUsers[3] },
    ],
    labels: [
      { id: 'tl-10', todo_id: 'todo-5', label_id: 'label-7', label: mockLabels[6] },
      { id: 'tl-11', todo_id: 'todo-5', label_id: 'label-8', label: mockLabels[7] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  // Done
  {
    id: 'todo-6',
    workspace_id: 'ws-1',
    category_id: 'cat-4',
    parent_id: null,
    title: 'Proje yapisinin kurulumu',
    description: 'Next.js 15, TypeScript, Tailwind CSS ve gerekli kutuphanelerin kurulumu.',
    status: 'done',
    priority: 'high',
    position: 0,
    due_date: '2024-01-05T00:00:00Z',
    start_date: '2024-01-01T00:00:00Z',
    completed_at: '2024-01-04T00:00:00Z',
    estimated_hours: 8,
    actual_hours: 6,
    progress: 100,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    assignees: [
      { id: 'assign-8', todo_id: 'todo-6', user_id: 'user-1', assigned_at: '2024-01-01T00:00:00Z', user: mockUsers[0] },
    ],
    labels: [
      { id: 'tl-12', todo_id: 'todo-6', label_id: 'label-2', label: mockLabels[1] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  {
    id: 'todo-7',
    workspace_id: 'ws-1',
    category_id: 'cat-4',
    parent_id: null,
    title: 'CI/CD pipeline kurulumu',
    description: 'GitHub Actions ile otomatik test ve deployment.',
    status: 'done',
    priority: 'medium',
    position: 1,
    due_date: '2024-01-08T00:00:00Z',
    start_date: '2024-01-05T00:00:00Z',
    completed_at: '2024-01-07T00:00:00Z',
    estimated_hours: 12,
    actual_hours: 10,
    progress: 100,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-5',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
    assignees: [
      { id: 'assign-9', todo_id: 'todo-7', user_id: 'user-5', assigned_at: '2024-01-03T00:00:00Z', user: mockUsers[4] },
    ],
    labels: [
      { id: 'tl-13', todo_id: 'todo-7', label_id: 'label-3', label: mockLabels[2] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [],
    time_entries: [],
  },
  // Blocked
  {
    id: 'todo-8',
    workspace_id: 'ws-1',
    category_id: 'cat-5',
    parent_id: null,
    title: 'Odeme entegrasyonu',
    description: 'Stripe/Iyzico odeme sistemi entegrasyonu. API anahtarlari bekleniyor.',
    status: 'blocked',
    priority: 'high',
    position: 0,
    due_date: '2024-02-25T00:00:00Z',
    start_date: '2024-01-20T00:00:00Z',
    completed_at: null,
    estimated_hours: 32,
    actual_hours: 4,
    progress: 10,
    is_recurring: false,
    recurrence_pattern: null,
    created_by: 'user-2',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
    assignees: [
      { id: 'assign-10', todo_id: 'todo-8', user_id: 'user-2', assigned_at: '2024-01-15T00:00:00Z', user: mockUsers[1] },
      { id: 'assign-11', todo_id: 'todo-8', user_id: 'user-3', assigned_at: '2024-01-15T00:00:00Z', user: mockUsers[2] },
    ],
    labels: [
      { id: 'tl-14', todo_id: 'todo-8', label_id: 'label-2', label: mockLabels[1] },
      { id: 'tl-15', todo_id: 'todo-8', label_id: 'label-6', label: mockLabels[5] },
    ],
    checklist_items: [],
    subtasks: [],
    comments: [],
    attachments: [],
    dependencies: [
      { id: 'dep-1', todo_id: 'todo-8', depends_on_id: 'todo-3', dependency_type: 'blocked_by' },
    ],
    time_entries: [],
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    workspace_id: 'ws-1',
    name: 'Backlog',
    color: '#6b7280',
    icon: 'inbox',
    position: 0,
    is_collapsed: false,
    wip_limit: null,
    todos: mockTodos.filter(t => t.category_id === 'cat-1'),
  },
  {
    id: 'cat-2',
    workspace_id: 'ws-1',
    name: 'Devam Ediyor',
    color: '#3b82f6',
    icon: 'play',
    position: 1,
    is_collapsed: false,
    wip_limit: 5,
    todos: mockTodos.filter(t => t.category_id === 'cat-2'),
  },
  {
    id: 'cat-3',
    workspace_id: 'ws-1',
    name: 'Incelemede',
    color: '#f59e0b',
    icon: 'eye',
    position: 2,
    is_collapsed: false,
    wip_limit: 3,
    todos: mockTodos.filter(t => t.category_id === 'cat-3'),
  },
  {
    id: 'cat-4',
    workspace_id: 'ws-1',
    name: 'Tamamlandi',
    color: '#10b981',
    icon: 'check',
    position: 3,
    is_collapsed: false,
    wip_limit: null,
    todos: mockTodos.filter(t => t.category_id === 'cat-4'),
  },
  {
    id: 'cat-5',
    workspace_id: 'ws-1',
    name: 'Engellendi',
    color: '#ef4444',
    icon: 'ban',
    position: 4,
    is_collapsed: false,
    wip_limit: null,
    todos: mockTodos.filter(t => t.category_id === 'cat-5'),
  },
];

// Mock Comments
export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    todo_id: 'todo-3',
    user_id: 'user-1',
    parent_id: null,
    content: '@elif Google OAuth icin callback URL ayarlandi mi?',
    is_edited: false,
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-18T10:00:00Z',
    user: mockUsers[0],
    replies: [
      {
        id: 'comment-2',
        todo_id: 'todo-3',
        user_id: 'user-2',
        parent_id: 'comment-1',
        content: 'Evet, production ve development icin ayri ayri ayarladim.',
        is_edited: false,
        created_at: '2024-01-18T10:30:00Z',
        updated_at: '2024-01-18T10:30:00Z',
        user: mockUsers[1],
        replies: [],
        mentions: [],
      },
    ],
    mentions: [{ id: 'mention-1', comment_id: 'comment-1', user_id: 'user-2', user: mockUsers[1] }],
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'user-1',
    type: 'mention',
    title: 'Yeni bahsetme',
    message: 'Elif sizi bir yorumda bahsetti',
    link: '/todo/todo-3',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'user-1',
    type: 'assignment',
    title: 'Yeni gorev atamasi',
    message: 'Size "Kullanici dashboard tasarimi" gorevi atandi',
    link: '/todo/todo-1',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'user-1',
    type: 'due_date',
    title: 'Yaklasan son tarih',
    message: '"Kullanici kimlik dogrulama" gorevi yarin bitiyor',
    link: '/todo/todo-3',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    workspace_id: 'ws-1',
    user_id: 'user-2',
    action: 'status_changed',
    entity_type: 'todo',
    entity_id: 'todo-5',
    old_values: { status: 'in_progress' },
    new_values: { status: 'in_review' },
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    user: mockUsers[1],
  },
  {
    id: 'log-2',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action: 'created',
    entity_type: 'todo',
    entity_id: 'todo-1',
    old_values: null,
    new_values: { title: 'Kullanici dashboard tasarimi' },
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    user: mockUsers[0],
  },
  {
    id: 'log-3',
    workspace_id: 'ws-1',
    user_id: 'user-3',
    action: 'comment_added',
    entity_type: 'comment',
    entity_id: 'comment-1',
    old_values: null,
    new_values: { todo_id: 'todo-3' },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    user: mockUsers[2],
  },
];
